### ISSUE TITLE
Provide for uploading a file collection

### ISSUE THREAD

**Issue by Primetalk** [open-jumpco/s3-plugin#10]
Currently there are two options - single file upload and directory upload.
It would be convenient to also support uploading files from a file collection. In particular, output of another task. (Uploading a directory is not enough as that directory might also contain other files as well.)

There is a potential problem though. If the provided file collection contains files from different folders and those files have the same name.

**Comment by corneil** [comment]
Thank you for a great suggestion.
It should be easy for upload.
On the download we can consider adding support for set of names that are relative to the directory.
Will look at it over the weekend.

**Comment by corneil** [comment]
Renamed `fileCollection` to `files`

**Comment by Primetalk** [comment]
Thank you for promptly publishing the newer version!
